### ISSUE TITLE
Cordova Build Problem

### ISSUE THREAD

**Issue by bonanhel** [realtime-framework/Messaging#4]
Hello,

there is a problem while building app for android. It seems that plugin is using an outdated way to declare dependencies such as android-support or play-services-gcm.

As standalone plugin there is no problem. If you try to add another plugin like background geolocation causes gradle to fail.

Build error is :
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2.

Regards,
Vangelis

**Comment by realtime-framework** [comment]
Thanks for the feedback @bonanhel. We are working on a new version release with this issue fixed. It's expected later today. Sorry for the inconvenience.

**Comment by realtime-framework** [comment]
Fixed by https://github.com/realtime-framework/CordovaPush/commit/247e5ef967e22e0d0ce57eb46500f9a53652f56e

A new version 0.1.13 was pushed to npm, please update your project.
